"""Add public_id to ImagenProducto

Revision ID: 0b12d86d1de1
Revises: a1d942dcdada
Create Date: 2025-07-20 07:50:14.427705

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0b12d86d1de1'
down_revision = 'a1d942dcdada'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imagenes_productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id', sa.String(length=255), nullable=True))

    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.alter_column('direccion_envio',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=False)
        batch_op.drop_column('numero_identificacion_cliente')
        batch_op.drop_column('direccion_cliente')
        batch_op.drop_column('metodo_pago')
        batch_op.drop_column('apellidos_cliente')
        batch_op.drop_column('departamento_cliente')
        batch_op.drop_column('razon_social_factura')
        batch_op.drop_column('provincia_cliente')
        batch_op.drop_column('nombre_cliente')
        batch_op.drop_column('numero_factura')
        batch_op.drop_column('telefono_envio')
        batch_op.drop_column('metodo_entrega')
        batch_op.drop_column('tipo_documento_factura')
        batch_op.drop_column('tipo_documento_cliente')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_documento_cliente', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True))
        batch_op.add_column(sa.Column('tipo_documento_factura', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True))
        batch_op.add_column(sa.Column('metodo_entrega', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
        batch_op.add_column(sa.Column('telefono_envio', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=15), nullable=True))
        batch_op.add_column(sa.Column('numero_factura', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True))
        batch_op.add_column(sa.Column('nombre_cliente', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True))
        batch_op.add_column(sa.Column('provincia_cliente', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True))
        batch_op.add_column(sa.Column('razon_social_factura', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
        batch_op.add_column(sa.Column('departamento_cliente', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True))
        batch_op.add_column(sa.Column('apellidos_cliente', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True))
        batch_op.add_column(sa.Column('metodo_pago', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True))
        batch_op.add_column(sa.Column('direccion_cliente', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
        batch_op.add_column(sa.Column('numero_identificacion_cliente', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True))
        batch_op.alter_column('direccion_envio',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=True)

    with op.batch_alter_table('imagenes_productos', schema=None) as batch_op:
        batch_op.drop_column('public_id')

    # ### end Alembic commands ###
