"""Añade rol a Usuario

Revision ID: 44a89c4a162f
Revises: f0e62d7ddef0
Create Date: 2025-07-11 17:32:19.019539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44a89c4a162f'
down_revision = 'f0e62d7ddef0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=80), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
