"""Migracion inicial completa con ajustes de nullable

Revision ID: bbf77c8f50c9
Revises: 
Create Date: 2025-07-10 17:50:02.612355

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bbf77c8f50c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.alter_column('estado_venta',
               existing_type=mysql.ENUM('pendiente', 'completado', 'enviado', 'entregado', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('cliente_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_index(batch_op.f('id'))

    with op.batch_alter_table('ventas_productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.alter_column('cantidad',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_index(batch_op.f('ventaproducto_id'))
        batch_op.drop_column('precio')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventas_productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio', mysql.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.create_index(batch_op.f('ventaproducto_id'), ['ventaproducto_id'], unique=True)
        batch_op.alter_column('cantidad',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('precio_unitario')

    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('id'), ['id'], unique=True)
        batch_op.alter_column('cliente_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('estado_venta',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('pendiente', 'completado', 'enviado', 'entregado', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)

    # ### end Alembic commands ###
