"""Añade precio_compra a Producto

Revision ID: f0e62d7ddef0
Revises: bbf77c8f50c9
Create Date: 2025-07-11 15:56:08.605174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0e62d7ddef0'
down_revision = 'bbf77c8f50c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio_compra', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_column('precio_compra')

    # ### end Alembic commands ###
